name: javed
on: 
  workflow_dispatch:
jobs: 
  terraform:
    runs-on: ubantu-latest
   
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
      - name: Azure login
        uses: azure/login@v3
        with:
          creds: |
            {
              "clientSecret":  5a0fd6ec-0020-4d20-9fb4-4817fa09c72b",
              "subscriptionId":  "7f5d9e48-dc3a-4e43-89ee-2f65015f2837",
              "tenantId":  "4611c619-c77c-404a-b26f-b286f3681168",
              "clientId":  "0c401359-9aa4-43a3-a26d-d1f0df746d57"           
             }
      - name: Terraform init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan
      - name: Terraform apply
        run: terraform apply -auto-approve
    
          


        
